Repository ICT2x01-P3-4/ict2x01-p3-4, pull requests merged in 2021-11, with the labels that each got.

#120 Feature/puzzle management apis
  app/__init__.py
  app/controllers/puzzle.py
  app/controllers/puzzle_management.py
  app/controllers/puzzles_api_controller.py
  app/controllers/users_api_controller.py
  app/models/car.py
  app/models/puzzle.py
  app/models/step.py
  app/models/user.py
  app/routes/api_bp.py
  app/routes/puzzle_bp.py
Labels: backend, development

#121 Feature/puzzle management apis
  app/controllers/puzzle.py
  app/controllers/puzzle_management.py
  app/models/puzzle.py
  app/models/step.py
  app/models/user.py
Labels: backend, development

#124 added feature tailwind in new feature branch
  .gitignore
  app/controllers/app_controller.py
  app/static/css/main.css
  app/static/package-lock.json
  app/static/package.json
  app/static/src/tailwind.css
  app/templates/index.html
Labels: development

#125 Management/restructure project
  app/__init__.py
  app/controllers/admin.py
  app/controllers/apis/puzzle.py
  app/controllers/puzzle_management.py
  app/models/puzzle.py
  app/routes/admin_bp.py
  app/routes/api_bp.py
  app/routes/app_bp.py
  app/templates/404.html
  app/templates/admin/create_puzzle.html
  app/templates/admin/edit_puzzle.html
  app/templates/admin/index.html
  app/templates/admin/profile.html
  app/templates/admin/puzzle.html
  app/templates/freestyle_mode.html
  app/templates/puzzle_mode.html
Labels: backend

#126 Feature/puzzle management apis
  app/routes/api_bp.py
  app/routes/puzzle_bp.py
  app/static/package-lock.json
Labels: backend

#127 Implement base template
  app/templates/404.html
  app/templates/admin/index.html
  app/templates/admin/puzzle.html
  app/templates/puzzle_mode.html
  app/templates/shared/base.html
  app/templates/shared/nav.html
Labels: frontend

#128 Management/readme
  .env.example
  README.md
Labels: documentation

#129 Feature/user auth
  app/__init__.py
  app/controllers/admin.py
  app/routes/admin_bp.py
  app/routes/api_bp.py
  requirements.txt
Labels: backend

#132 fix: import error in api_bp.py
  app/routes/api_bp.py
Labels: bug

#134 Management/restructure backend
  app/apis/car.py
  app/apis/puzzle.py
  app/controllers/admin_controller.py
  app/models/puzzle.py
  app/routes/admin_bp.py
  app/routes/api_bp.py
Labels: backend

#135 Feature/car apis
  app/apis/car.py
  app/apis/puzzle.py
  app/models/Queue.py
  app/models/car.py
  app/models/step.py
  app/routes/api_bp.py
Labels: backend

#136 Management/restructure backend
  app/apis/car_api.py
  app/apis/puzzle.py
  app/apis/puzzle_api.py
  app/controllers/admin_controller.py
  app/models/car.py
  app/models/car_model.py
  app/models/entities/car_entity.py
  app/models/entities/puzzle_entity.py
  app/models/entities/step_entity.py
  app/models/entities/user_entity.py
  app/models/puzzle.py
  app/models/puzzle_model.py
  app/models/queue_model.py
  app/models/user.py
  app/models/user_model.py
  app/routes/admin_bp.py
  app/routes/api_bp.py
Labels: backend

#141 Implement data seeder
  app/__init__.py
  app/dataseeder.py
Labels: backend, development

#138 Add node_modules to gitignore
  .gitignore
Labels: backend

#143 Add script block and remove nav block
  app/templates/shared/base.html
Labels: frontend

#144 Feature/user-auth-api
  app/controllers/apis/freestyle.py
  app/controllers/app_controller.py
  app/models/user_model.py
Labels: backend, development

#145 Feature/userlogin
  app/controllers/app_controller.py
  app/routes/app_bp.py
  app/templates/index.html
  app/templates/shared/nav.html
  app/templates/user_home.html
Labels: development, frontend

#146 Feature/freestyle mode
  app/controllers/app_controller.py
  app/routes/app_bp.py
  app/templates/freestyle_mode.html
  app/templates/user_home.html
Labels: development, frontend

#147 Fix/templating
  app/templates/freestyle_mode.html
  app/templates/shared/base.html
  app/templates/user_home.html
Labels: development, frontend

#150 Feature/admin UI
  app/routes/admin_bp.py
  app/static/package-lock.json
  app/templates/admin/create_puzzle.html
  app/templates/admin/index.html
  app/templates/admin/login.html
  app/templates/admin/profile.html
  app/templates/admin/puzzle.html
Labels: development, frontend

#151 Feature/error page
  app/static/css/404.css
  app/templates/404.html
Labels: development, frontend

#152 Feature/user auth api
  .gitignore
  app/__init__.py
  app/controllers/admin_controller.py
  app/controllers/app_controller.py
  app/dataseeder.py
  app/models/user_model.py
  app/routes/admin_bp.py
  app/routes/app_bp.py
  app/templates/admin/login.html
  app/templates/index.html
  app/templates/user_home.html
  requirements.txt
Labels: backend, development, frontend

#153 Feature/car apis
  .gitignore
  app/apis/car_api.py
  app/models/car_model.py
  app/models/queue_model.py
  app/routes/api_bp.py
  app/templates/admin/create_puzzle.html
  app/templates/admin/profile.html
Labels: backend, development

#154 Feature/freestyle backend
  app/apis/freestyle_api.py
  app/routes/api_bp.py
  app/static/js/freestyle.js
  app/templates/freestyle_mode.html
Labels: backend, development, frontend

#156 Feature/UI improvements
  app/controllers/app_controller.py
  app/static/css/.gitkeep
  app/static/css/main.css
  app/static/js/freestyle.js
  app/templates/freestyle_mode.html
  app/templates/index.html
  app/templates/puzzle_mode.html
  app/templates/shared/nav.html
  app/templates/shared/wave.html
  app/templates/user_home.html
Labels: development, frontend

#158 Feature/puzzle backend
  app/apis/car_api.py
  app/apis/freestyle_api.py
  app/apis/puzzle_api.py
  app/controllers/apis/freestyle.py
  app/models/puzzle_model.py
  app/models/queue_model.py
  app/models/user_model.py
  app/routes/api_bp.py
Labels: backend, development

#159 Return a string when starting car
  app/apis/car_api.py
Labels: backend, development

#160 refactor: rename variable for clarity
  app/controllers/app_controller.py
  app/models/user_model.py
  app/templates/index.html
Labels: development

#162 fix: centering text and widen circle in user
  app/templates/index.html
Labels: bug, development, frontend

#163 Completed UI functionalities for puzzle mode
  app/static/css/main.css
  app/static/js/puzzle.js
  app/templates/puzzle_mode.html
Labels: development, frontend
