Repository ICT2x01-P3-4/ict2x01-p3-4, pull requests merged in 2021-12, with the labels that each got.

#164 Feature/puzzle backend
  app/apis/puzzle_api.py
  app/controllers/app_controller.py
  app/models/entities/puzzle_entity.py
  app/models/puzzle_model.py
  app/models/queue_model.py
  app/models/user_model.py
  app/routes/api_bp.py
  app/static/css/main.css
  app/static/js/freestyle.js
  app/static/js/puzzle.js
  app/templates/freestyle_mode.html
  app/templates/puzzle_mode.html
  app/templates/shared/base.html
  app/templates/shared/wave.html
  app/templates/user_home.html
Labels: backend, development, frontend

#165 fixed minor UI issues
  app/static/js/puzzle.js
  app/templates/puzzle_mode.html
Labels: development, frontend

#166 Improved the UI for freestyle mode
  app/templates/freestyle_mode.html
Labels: enhancement, development, frontend

#167 docs: Revised Setup configuration and Workflow
  README.md
Labels: documentation

#169 Change to smaller wave
  app/templates/shared/wave.html
Labels: development, frontend

#168 Feature/admin UI manage puzzle home
  app/static/js/createpuzzle.js
  app/templates/admin/create_puzzle.html
  app/templates/admin/index.html
  app/templates/admin/login.html
  app/templates/admin/puzzle.html
Labels: enhancement, development, frontend

#170 fix: user session redirect in game mode controller
  app/controllers/app_controller.py
Labels: bug, backend, development

#173 Feature/UI improvements
  app/templates/admin/index.html
Labels: development, frontend

#174 Feature/usermanagement backend
  app/apis/admin_api.py
  app/controllers/admin_controller.py
  app/models/user_model.py
  app/routes/api_bp.py
  app/static/js/adminProfile.js
  app/templates/admin/profile.html
Labels: backend, development, frontend

#175 Feature/UI improvements
  app/templates/admin/profile.html
  app/templates/freestyle_mode.html
  app/templates/puzzle_mode.html
  app/templates/shared/base.html
Labels: development, frontend

#176 Redirect user to login page if not in session
  app/controllers/admin_controller.py
  app/templates/index.html
Labels: backend, development

#177 Admin UI - updated manage puzzle homepage navbar
  app/templates/admin/puzzle.html
Labels: development, frontend

#178 Feature/UI improvements
  app/static/js/freestyle.js
  app/static/js/puzzle.js
  app/templates/freestyle_mode.html
  app/templates/puzzle_mode.html
Labels: development, frontend

#180 Feature/admin UI manage puzzle home
  app/static/js/createpuzzle.js
  app/templates/admin/create_puzzle.html
Labels: development, frontend

#183 Fix/admin puzzle
  app/static/js/adminPuzzle.js
  app/templates/admin/puzzle.html
Labels: backend, development

#186 Completed UI functionality for viewing puzzle details
  app/controllers/admin_controller.py
  app/routes/admin_bp.py
  app/static/js/viewPuzzle.js
  app/templates/admin/profile.html
  app/templates/admin/puzzle.html
  app/templates/admin/view_puzzle.html
Labels: development, frontend

#187 Feature/tutorial
  app/static/js/tutorial.js
  app/templates/index.html
Labels: development, frontend

#190 Feature/UI improvements
  app/templates/user_home.html
Labels: frontend

#191 Fix the client side input validation for creating and editing puzzle
  app/controllers/admin_controller.py
  app/routes/admin_bp.py
  app/static/js/createpuzzle.js
  app/static/js/editpuzzle.js
  app/templates/admin/create_puzzle.html
  app/templates/admin/edit_puzzle.html
Labels: development, frontend

#193 Change button text back to step after waypoint is updated
  app/controllers/admin_controller.py
  app/models/entities/puzzle_entity.py
  app/models/puzzle_model.py
  app/routes/admin_bp.py
  app/static/js/createpuzzle.js
  app/static/js/editpuzzle.js
  app/static/js/puzzle.js
  app/static/js/viewPuzzle.js
  app/templates/admin/edit_puzzle.html
  app/templates/admin/puzzle.html
  app/templates/admin/view_puzzle.html
  app/templates/puzzle_mode.html
Labels: backend, development, frontend

#194 fixed the client side validation for puzzle management
  app/static/js/createpuzzle.js
  app/static/js/editpuzzle.js
  app/static/js/viewPuzzle.js
  app/templates/admin/view_puzzle.html
Labels: development, frontend

#195 Feature/puzzle backend
  app/apis/puzzle_api.py
  app/models/puzzle_model.py
  app/static/js/adminPuzzle.js
  app/static/js/createpuzzle.js
  app/static/js/puzzle.js
  app/templates/admin/puzzle.html
Labels: backend, development, frontend

#196 Feature/puzzle backend
  app/models/puzzle_model.py
Labels: backend, development

#200 Validate user name
  app/models/user_model.py
Labels: backend, development

#201 Clean up and document code
  app/apis/admin_api.py
  app/apis/puzzle_api.py
  app/models/puzzle_model.py
  app/static/js/editpuzzle.js
Labels: backend, development

#202 Fix puzzle not showing
  app/models/puzzle_model.py
  app/templates/puzzle_mode.html
Labels: backend, development, frontend

#203 Feature/car apis
  app/apis/car_api.py
  app/templates/admin/edit_puzzle.html
Labels: backend, development

#204 chore: diff config for test and prod
  .gitignore
  app/__init__.py
  app/models/__init__.py
  app/models/puzzle_model.py
  carstep.py
  config.py.example
Labels: backend, development

#205 Fix button alignments
  app/templates/admin/index.html
Labels: development, frontend

#206 Upload the document for updated test cases
  docs/M3_Updated_Test_Cases.pdf
Labels: documentation

#207 Updated readme for UAT section
  README.md
Labels: documentation

#208 cleaned up code for frontend
  app/static/js/createpuzzle.js
  app/static/js/editpuzzle.js
  app/static/js/freestyle.js
  app/static/js/puzzle.js
  app/templates/admin/view_puzzle.html
  app/templates/freestyle_mode.html
  app/templates/puzzle_mode.html
Labels: development, frontend

#209 Feature/car apis
  app/apis/car_api.py
Labels: backend, development

#211 Test/puzzle model
  app/models/puzzle_model.py
  test_coverage.py
  test_data/puzzles.json
  test_data/queue.json
Labels: documentation, backend, test

#210 Management/readme
  README.md
  app/models/__init__.py
Labels: documentation

#212 Increase badge size
  README.md
Labels: documentation

#214 chore" added necessary dependencies
  requirements.txt
Labels: documentation

#215 Management/readme
  README.md
  test_data/queue.json
Labels: documentation

#216 fix: removed unncessary if statement
  test_coverage.py
Labels: documentation

#217 Management/readme
  README.md
Labels: documentation
